module.exports = {
  apps: [
    {
      name: 'itaxi-api',
      script: './server/dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/gateway-err.log',
      out_file: './logs/gateway-out.log',
      log_file: './logs/gateway-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5000,
        SERVICE_NAME: 'itaxi-api',
        REDIS_URL: process.env.REDIS_URL,
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5000,
        SERVICE_NAME: 'itaxi-api',
        REDIS_URL: process.env.REDIS_URL,
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'auth-service',
      script: './services/auth-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/auth-err.log',
      out_file: './logs/auth-out.log',
      log_file: './logs/auth-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5001,
        SERVICE_NAME: 'auth-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || 'refresh_secret_default',
        REDIS_URL: process.env.REDIS_URL,
        WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
        WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
        WHATSAPP_APP_SECRET: process.env.WHATSAPP_APP_SECRET,
        WHATSAPP_VERIFY_TOKEN: process.env.WHATSAPP_VERIFY_TOKEN,
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5001,
        SERVICE_NAME: 'auth-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
        WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
        WHATSAPP_APP_SECRET: process.env.WHATSAPP_APP_SECRET,
        WHATSAPP_VERIFY_TOKEN: process.env.WHATSAPP_VERIFY_TOKEN,
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'ride-service',
      script: './services/ride-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/ride-err.log',
      out_file: './logs/ride-out.log',
      log_file: './logs/ride-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5002,
        SERVICE_NAME: 'ride-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        AUTH_SERVICE_URL: 'http://localhost:5001',
        DISPATCH_SERVICE_URL: 'http://localhost:5004',
        NOTIFICATION_SERVICE_URL: 'http://localhost:5006',
        FRAUD_SERVICE_URL: 'http://localhost:5007',
        ANALYTICS_SERVICE_URL: 'http://localhost:5008',
        LOYALTY_SERVICE_URL: 'http://localhost:5010',
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5002,
        SERVICE_NAME: 'ride-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        AUTH_SERVICE_URL: process.env.AUTH_SERVICE_URL || 'http://localhost:5001',
        DISPATCH_SERVICE_URL: process.env.DISPATCH_SERVICE_URL || 'http://localhost:5004',
        NOTIFICATION_SERVICE_URL: process.env.NOTIFICATION_SERVICE_URL || 'http://localhost:5006',
        FRAUD_SERVICE_URL: process.env.FRAUD_SERVICE_URL || 'http://localhost:5007',
        ANALYTICS_SERVICE_URL: process.env.ANALYTICS_SERVICE_URL || 'http://localhost:5008',
        LOYALTY_SERVICE_URL: process.env.LOYALTY_SERVICE_URL || 'http://localhost:5010',
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'payment-service',
      script: './services/payment-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/payment-err.log',
      out_file: './logs/payment-out.log',
      log_file: './logs/payment-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5003,
        SERVICE_NAME: 'payment-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
        WALLET_SERVICE_URL: 'http://localhost:5005',
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5003,
        SERVICE_NAME: 'payment-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
        WALLET_SERVICE_URL: process.env.WALLET_SERVICE_URL || 'http://localhost:5005',
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'dispatch-service',
      script: './services/dispatch-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/dispatch-err.log',
      out_file: './logs/dispatch-out.log',
      log_file: './logs/dispatch-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5004,
        SERVICE_NAME: 'dispatch-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        NOTIFICATION_SERVICE_URL: 'http://localhost:5006',
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5004,
        SERVICE_NAME: 'dispatch-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        NOTIFICATION_SERVICE_URL: process.env.NOTIFICATION_SERVICE_URL || 'http://localhost:5006',
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'wallet-service',
      script: './services/wallet-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/wallet-err.log',
      out_file: './logs/wallet-out.log',
      log_file: './logs/wallet-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5005,
        SERVICE_NAME: 'wallet-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        PAYMENT_SERVICE_URL: 'http://localhost:5003',
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5005,
        SERVICE_NAME: 'wallet-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        PAYMENT_SERVICE_URL: process.env.PAYMENT_SERVICE_URL || 'http://localhost:5003',
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'notification-service',
      script: './services/notification-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/notification-err.log',
      out_file: './logs/notification-out.log',
      log_file: './logs/notification-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5006,
        SERVICE_NAME: 'notification-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
        WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5006,
        SERVICE_NAME: 'notification-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        WHATSAPP_ACCESS_TOKEN: process.env.WHATSAPP_ACCESS_TOKEN,
        WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'fraud-service',
      script: './services/fraud-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/fraud-err.log',
      out_file: './logs/fraud-out.log',
      log_file: './logs/fraud-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5007,
        SERVICE_NAME: 'fraud-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        NOTIFICATION_SERVICE_URL: 'http://localhost:5006',
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5007,
        SERVICE_NAME: 'fraud-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        NOTIFICATION_SERVICE_URL: process.env.NOTIFICATION_SERVICE_URL || 'http://localhost:5006',
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'analytics-service',
      script: './services/analytics-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/analytics-err.log',
      out_file: './logs/analytics-out.log',
      log_file: './logs/analytics-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5008,
        SERVICE_NAME: 'analytics-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5008,
        SERVICE_NAME: 'analytics-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'corporate-service',
      script: './services/corporate-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/corporate-err.log',
      out_file: './logs/corporate-out.log',
      log_file: './logs/corporate-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5009,
        SERVICE_NAME: 'corporate-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        DISPATCH_SERVICE_URL: 'http://localhost:5004',
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5009,
        SERVICE_NAME: 'corporate-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        DISPATCH_SERVICE_URL: process.env.DISPATCH_SERVICE_URL || 'http://localhost:5004',
        LOG_LEVEL: 'warn'
      }
    },
    {
      name: 'loyalty-service',
      script: './services/loyalty-service/index.js',
      instances: 1,
      exec_mode: 'fork',
      merge_logs: true,
      max_memory_restart: '1G',
      error_file: './logs/loyalty-err.log',
      out_file: './logs/loyalty-out.log',
      log_file: './logs/loyalty-combined.log',
      time: true,
      env: {
        NODE_ENV: 'development',
        PORT: 5010,
        SERVICE_NAME: 'loyalty-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        NOTIFICATION_SERVICE_URL: 'http://localhost:5006',
        LOG_LEVEL: 'info'
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5010,
        SERVICE_NAME: 'loyalty-service',
        DATABASE_URL: process.env.DATABASE_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        NOTIFICATION_SERVICE_URL: process.env.NOTIFICATION_SERVICE_URL || 'http://localhost:5006',
        LOG_LEVEL: 'warn'
      }
    }
  ]
};